scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8888']
      - targets: ['host.docker.internal:8090']
      - targets: ['host.docker.internal:8080']
      - targets: ['host.docker.internal:8081']
      - targets: ['host.docker.internal:8082']
      - targets: ['host.docker.internal:9093']
        labels:
          application: 'My Spring Boot Application'
